CREATE DATABASE hospital
WITH ENCODING 'UTF8'
TEMPLATE template0
LC_COLLATE='en_US.UTF-8'
LC_CTYPE='en_US.UTF-8';

CREATE DATABASE idc_pizza
WITH ENCODING 'UTF8'
TEMPLATE template0
LC_COLLATE='en_US.UTF-8'
LC_CTYPE='en_US.UTF-8';

CREATE DATABASE mystery
WITH ENCODING 'UTF8'
TEMPLATE template0
LC_COLLATE='en_US.UTF-8'
LC_CTYPE='en_US.UTF-8';

